#!/bin/bash

sudo apt-get install -y neovim \
	tig \
	git \
	gcc \
	gcc-c++ \
	ripgrep \
	fd \
	fzf \
	lazygit \
	pinentry-bash \
	pinentry-common \
	tree-sitter-cli \
	python3-module-neovim \
	ruby \
	gem \
	node \
	npm \
	pip \
	task \
    tree \
    translate-shell

pip install tasklib

homedir="$(realpath ~)"
sudo cp -rf $homedir/.scripts/ /root/
sudo cp -rf $homedir/.scripts/.bashrc.root /root/.bashrc

